/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_medwalletapp_RustBridgeModule */

#ifndef _Included_com_medwalletapp_RustBridgeModule
#define _Included_com_medwalletapp_RustBridgeModule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_medwalletapp_RustBridgeModule
 * Method:    hello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_medwalletapp_RustBridgeModule_hello
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_medwalletapp_RustBridgeModule
 * Method:    nativeEncryption
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_medwalletapp_RustBridgeModule_nativeEncryption
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
