/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_medwalletapp_RustBridgeModule */

#ifndef _Included_com_medwalletapp_RustBridgeModule
#define _Included_com_medwalletapp_RustBridgeModule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_medwalletapp_RustBridgeModule
 * Method:    createAES
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_medwalletapp_RustBridgeModule_createAES
  (JNIEnv *, jclass);

/*
 * Class:     com_medwalletapp_RustBridgeModule
 * Method:    encryptByteArray
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_medwalletapp_RustBridgeModule_encryptByteArray
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_medwalletapp_RustBridgeModule
 * Method:    decryptByteArray
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_medwalletapp_RustBridgeModule_decryptByteArray
  (JNIEnv *, jclass, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
